
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'AC ADD AND AP DIV Diff ELSE Equal FC FP GoE Greater IF IGUAL INT LoE Lower MOD MUL NOT Nint OR SUB VAR WHILEExpression : Values Expression : Expression ADD ValuesExpression : Expression SUB ValuesValues : ValueValues : Values MUL ValueValues : Values DIV ValueValues : Values MOD ValueValue : NintValue : VARValue : AP Expression FP'
    
_lr_action_items = {'Nint':([0,6,7,8,9,10,11,],[4,4,4,4,4,4,4,]),'VAR':([0,6,7,8,9,10,11,],[5,5,5,5,5,5,5,]),'AP':([0,6,7,8,9,10,11,],[6,6,6,6,6,6,6,]),'$end':([1,2,3,4,5,13,14,15,16,17,18,],[0,-1,-4,-8,-9,-2,-3,-5,-6,-7,-10,]),'ADD':([1,2,3,4,5,12,13,14,15,16,17,18,],[7,-1,-4,-8,-9,7,-2,-3,-5,-6,-7,-10,]),'SUB':([1,2,3,4,5,12,13,14,15,16,17,18,],[8,-1,-4,-8,-9,8,-2,-3,-5,-6,-7,-10,]),'FP':([2,3,4,5,12,13,14,15,16,17,18,],[-1,-4,-8,-9,18,-2,-3,-5,-6,-7,-10,]),'MUL':([2,3,4,5,13,14,15,16,17,18,],[9,-4,-8,-9,9,9,-5,-6,-7,-10,]),'DIV':([2,3,4,5,13,14,15,16,17,18,],[10,-4,-8,-9,10,10,-5,-6,-7,-10,]),'MOD':([2,3,4,5,13,14,15,16,17,18,],[11,-4,-8,-9,11,11,-5,-6,-7,-10,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'Expression':([0,6,],[1,12,]),'Values':([0,6,7,8,],[2,2,13,14,]),'Value':([0,6,7,8,9,10,11,],[3,3,3,3,15,16,17,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> Expression","S'",1,None,None,None),
  ('Expression -> Values','Expression',1,'p_expression_simple','compiler_yacc.py',163),
  ('Expression -> Expression ADD Values','Expression',3,'p_expression_plus','compiler_yacc.py',167),
  ('Expression -> Expression SUB Values','Expression',3,'p_expression_less','compiler_yacc.py',174),
  ('Values -> Value','Values',1,'p_Values_simple','compiler_yacc.py',185),
  ('Values -> Values MUL Value','Values',3,'p_Values_1','compiler_yacc.py',190),
  ('Values -> Values DIV Value','Values',3,'p_Values_2','compiler_yacc.py',194),
  ('Values -> Values MOD Value','Values',3,'p_Values_3','compiler_yacc.py',198),
  ('Value -> Nint','Value',1,'p_Value_int','compiler_yacc.py',207),
  ('Value -> VAR','Value',1,'p_Value_var','compiler_yacc.py',212),
  ('Value -> AP Expression FP','Value',3,'p_Value_complex','compiler_yacc.py',216),
]
